# Generated by Django 5.2.4 on 2025-07-20 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_author_post_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
